/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phono_audio_codec_OpusCodec */

#ifndef _Included_com_phono_audio_codec_OpusCodec
#define _Included_com_phono_audio_codec_OpusCodec
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phono_audio_codec_OpusCodec_OPUS_SET_APPLICATION_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_SET_APPLICATION_REQUEST 4000L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_APPLICATION_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_APPLICATION_REQUEST 4001L
#undef com_phono_audio_codec_OpusCodec_OPUS_SET_BITRATE_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_SET_BITRATE_REQUEST 4002L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_BITRATE_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_BITRATE_REQUEST 4003L
#undef com_phono_audio_codec_OpusCodec_OPUS_SET_MAX_BANDWIDTH_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_SET_MAX_BANDWIDTH_REQUEST 4004L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_MAX_BANDWIDTH_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_MAX_BANDWIDTH_REQUEST 4005L
#undef com_phono_audio_codec_OpusCodec_OPUS_SET_VBR_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_SET_VBR_REQUEST 4006L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_VBR_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_VBR_REQUEST 4007L
#undef com_phono_audio_codec_OpusCodec_OPUS_SET_BANDWIDTH_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_SET_BANDWIDTH_REQUEST 4008L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_BANDWIDTH_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_BANDWIDTH_REQUEST 4009L
#undef com_phono_audio_codec_OpusCodec_OPUS_SET_COMPLEXITY_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_SET_COMPLEXITY_REQUEST 4010L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_COMPLEXITY_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_COMPLEXITY_REQUEST 4011L
#undef com_phono_audio_codec_OpusCodec_OPUS_SET_INBAND_FEC_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_SET_INBAND_FEC_REQUEST 4012L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_INBAND_FEC_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_INBAND_FEC_REQUEST 4013L
#undef com_phono_audio_codec_OpusCodec_OPUS_SET_PACKET_LOSS_PERC_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_SET_PACKET_LOSS_PERC_REQUEST 4014L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_PACKET_LOSS_PERC_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_PACKET_LOSS_PERC_REQUEST 4015L
#undef com_phono_audio_codec_OpusCodec_OPUS_SET_DTX_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_SET_DTX_REQUEST 4016L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_DTX_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_DTX_REQUEST 4017L
#undef com_phono_audio_codec_OpusCodec_OPUS_SET_VBR_CONSTRAINT_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_SET_VBR_CONSTRAINT_REQUEST 4020L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_VBR_CONSTRAINT_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_VBR_CONSTRAINT_REQUEST 4021L
#undef com_phono_audio_codec_OpusCodec_OPUS_SET_FORCE_CHANNELS_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_SET_FORCE_CHANNELS_REQUEST 4022L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_FORCE_CHANNELS_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_FORCE_CHANNELS_REQUEST 4023L
#undef com_phono_audio_codec_OpusCodec_OPUS_SET_SIGNAL_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_SET_SIGNAL_REQUEST 4024L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_SIGNAL_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_SIGNAL_REQUEST 4025L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_LOOKAHEAD_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_LOOKAHEAD_REQUEST 4027L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_SAMPLE_RATE_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_SAMPLE_RATE_REQUEST 4029L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_FINAL_RANGE_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_FINAL_RANGE_REQUEST 4031L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_PITCH_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_PITCH_REQUEST 4033L
#undef com_phono_audio_codec_OpusCodec_OPUS_SET_GAIN_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_SET_GAIN_REQUEST 4034L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_GAIN_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_GAIN_REQUEST 4045L
#undef com_phono_audio_codec_OpusCodec_OPUS_SET_LSB_DEPTH_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_SET_LSB_DEPTH_REQUEST 4036L
#undef com_phono_audio_codec_OpusCodec_OPUS_GET_LSB_DEPTH_REQUEST
#define com_phono_audio_codec_OpusCodec_OPUS_GET_LSB_DEPTH_REQUEST 4037L
#undef com_phono_audio_codec_OpusCodec_OPUS_APPLICATION_VOIP
#define com_phono_audio_codec_OpusCodec_OPUS_APPLICATION_VOIP 2048L
#undef com_phono_audio_codec_OpusCodec_PHONOSAMPLERATE
#define com_phono_audio_codec_OpusCodec_PHONOSAMPLERATE 16000L
#undef com_phono_audio_codec_OpusCodec_OPUS_CODEC
#define com_phono_audio_codec_OpusCodec_OPUS_CODEC 1073741824LL
#undef com_phono_audio_codec_OpusCodec_CHANNELS
#define com_phono_audio_codec_OpusCodec_CHANNELS 1L
/*
 * Class:     com_phono_audio_codec_OpusCodec
 * Method:    getDecoderSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_phono_audio_codec_OpusCodec_getDecoderSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phono_audio_codec_OpusCodec
 * Method:    getEncoderSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_phono_audio_codec_OpusCodec_getEncoderSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phono_audio_codec_OpusCodec
 * Method:    initEncoder
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_phono_audio_codec_OpusCodec_initEncoder
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_phono_audio_codec_OpusCodec
 * Method:    initDecoder
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_phono_audio_codec_OpusCodec_initDecoder
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_phono_audio_codec_OpusCodec
 * Method:    opusDecode
 * Signature: ([BI)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_phono_audio_codec_OpusCodec_opusDecode
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_phono_audio_codec_OpusCodec
 * Method:    opusEncode
 * Signature: ([S)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_phono_audio_codec_OpusCodec_opusEncode
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     com_phono_audio_codec_OpusCodec
 * Method:    opusSetCtl
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_phono_audio_codec_OpusCodec_opusSetCtl
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_phono_audio_codec_OpusCodec
 * Method:    opusGetCtl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_phono_audio_codec_OpusCodec_opusGetCtl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_phono_audio_codec_OpusCodec
 * Method:    freeCodec
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_phono_audio_codec_OpusCodec_freeCodec
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
